### PR TITLE
修复登录状态问题

### PR DESCRIPTION
**Pull request by zeus2615**
fix login status

### CODE REVIEW

**Comment by zfdang** [comment]
没啥必要，现在的int值说不定可以反映新消息的数量呢

**Comment by zeus2615** [comment]
这块的不正确，导致app里面很多记录登录状态的地方都不正常，譬如左侧菜单应该显示头像的，却显示未登录，右上角菜单应该是可以切换登录和下线功能的，现在永远都是登录

**Comment by zfdang** [comment]
原来我观察，水木对于user status返回的结果是不稳定的， 有的时候是int,有的时候是boolean. 

比如我的结果：

{"id":"mozilla",
"user_name":"Delivery Done!",
"face_url":"//images.newsmth.net/nForum/img/face_default_m.jpg",
"face_width":null,
"face_height":null,
"gender":"m",
"astro":"白羊座",
"life":"楠木",
"lifelevel":12,
"qq":null,
"msn":null,
"home_page":null,
"level":"用户",
"is_online":true,
"post_count":9232,
"last_login_time":1519616309,
"last_login_ip":"111.202.212.157",
"is_hide":true,
"is_activated":true,
"is_register":true,
"login_count":34127,
"is_admin":false,
"first_login_time":1066982906,
"stay_count":118183936,
"score_user":62961,
"score_manager":0,
"is_login":true,
"forum_totol_count":45983,
"forum_user_count":16411,
"forum_guest_count":29572,
"new_mail":false,
"full_mail":false,
"new_like":0,
"new_reply":0,
"new_at":0,
"new_msg":0,
"ajax_st":1,
"ajax_code":"0005",
"ajax_msg":"操作成功"}

**Comment by zfdang** [comment]
UserStatus.java line: 67也有注释，标明过这个问题

**Pull request closed without merging**
